# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: muvis-align
email: folterj@gmail.com
full_name: Joost de Folter
github_repository_url: provide later
github_username_or_organization: folterj
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: GNU GPL v3.0
module_name: muvis_align
plugin_name: napari-muvis-align
short_description: Image registration plugin using multiview-stitcher
