name: muvis-source-env
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.12.3
 - numpy
 - scipy
 - scikit-image
 - scikit-learn
 - dask
 - tifffile>=2023.9.26
 - zarr
 - ome-zarr
 - matplotlib
 - tqdm
 - pip
 - pip:
   - git+https://github.com/multiview-stitcher/multiview-stitcher.git@improve_global_opt
   - antspyx
   - opencv-python
   - spatial-image
   - multiscale-spatial-image
   - frc