name: multiview-stitcher-test-env
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.10
 - pyqt
 - napari
 - numpy
 - scipy
 - scikit-image
 - scikit-learn
 - dask
 - tifffile>=2023.9.26
 - matplotlib
 - tqdm
 - pip
 - pip:
   - -r requirements.txt
